### ISSUE TITLE
OSError: no file with expected extension

### ISSUE THREAD

**Issue by mxg007** [yanxp/PointNet#2]
teacher：
when I run show3d_ball.py,there is an error
Traceback (most recent call last):
  File "C:/Users/123456/Desktop/PointNet/PointNet-master_pytorch_yanxp/utils/show3d_ball.py", line 23, in <module>
    dll=np.ctypeslib.load_library(os.path.join(BASE_DIR, 'render_balls_so'),'.')
  File "F:\anaconda1\lib\site-packages\numpy\ctypeslib.py", line 155, in load_library
    raise OSError("no file with expected extension")
OSError: no file with expected extension

**Comment by yanxp** [comment]
hello,you can refer to https://github.com/charlesq34/pointnet2/tree/master/utils to compile it. Thanks!

**Comment by FandosA** [comment]
Hello, I compiled the cpp file with ```git``` and ```g++``` but I still get the error ```OSError: no file with expected extension```. Is there any solution to solve this on windows?

**Comment by ocpinfo** [comment]
I have got the same problem even if I compiled the render_ball_so.so successfully
